services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    ports:
      - ${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}
    volumes:
      - my-db:/var/lib/mysql
networks:
    cont:
        driver:  bridge
        enable_ipv6: false
volumes:
  my-db:
